# Multi language is not supported so Python needs to be installed ourselves.
# Ruby is default.

language: ruby

rvm:
  - 2.2.3

env:
- PYTHON=python3.4

#notifications:
#  irc:
#    - "irc.efnet.net#archivebot"

before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes --yes
  - sudo apt-get update -qq
  - wget https://bootstrap.pypa.io/get-pip.py

install:
  - bundle install --jobs=3 --retry=3 --deployment
  - cd plumbing && bundle install --jobs=3 --retry=3 --deployment && cd ..
  - sudo apt-get -qq install ircd-hybrid $PYTHON $PYTHON-dev rsync libzmq3-dev
  - sudo $PYTHON get-pip.py
  - travis_retry $PYTHON -m pip install -q -r pipeline/requirements.txt --user
  - travis_retry $PYTHON -m pip install -q nose pytest irc --user
  - sudo cp test/example_rsyncd.conf /etc/rsyncd.conf
  - $PYTHON -m pip install -q git+https://github.com/chfoo/huhhttp#egg=huhhttp --user

before_script:
  - curl -X PUT http://127.0.0.1:5984/archivebot
  - curl -X PUT http://127.0.0.1:5984/archivebot_logs

  - grep -v _rev db/design_docs/archive_urls.json > /tmp/archive_urls.json
  - curl -X PUT http://127.0.0.1:5984/archivebot/_design/archive_urls -d @/tmp/archive_urls.json

  - grep -v _rev db/design_docs/ignore_patterns.json > /tmp/ignore_patterns.json
  - curl -X PUT http://127.0.0.1:5984/archivebot/_design/ignore_patterns -d @/tmp/ignore_patterns.json

  - grep -v _rev db/design_docs/jobs.json > /tmp/jobs.json
  - curl -X PUT http://127.0.0.1:5984/archivebot/_design/jobs -d @/tmp/jobs.json

  - grep -v _rev db/design_docs/user_agents.json > /tmp/user_agents.json
  - curl -X PUT http://127.0.0.1:5984/archivebot/_design/user_agents -d @/tmp/user_agents.json

  # If ircd-hybrid is running (which currently happens with Ubuntu packages),
  # this will restart it.
  # If ircd-hybrid is not running (could happen in future), this will start it.
  - sudo /etc/init.d/ircd-hybrid restart

  - echo -e '\n\nRSYNC_ENABLE=true\n\n' | sudo tee -a /etc/default/rsync
  - sudo /etc/init.d/rsync restart

services:
  - redis-server
  - couchdb

script:
  - bundle exec rake
  - $PYTHON -m nose pipeline/
  - $PYTHON -m pytest test/validate_db.py
  - $PYTHON test/integration_runner.py
