# Multi language is not supported so Python needs to be installed ourselves.
# Ruby is default.

language: ruby

rvm:
  - 1.9.3

before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes --yes
  - sudo apt-get update -qq
  - wget https://bootstrap.pypa.io/get-pip.py

install:
  - bundle install --jobs=3 --retry=3 --deployment
  - sudo apt-get install ircd-hybrid python3.4 python3.4-dev rsync
  - sudo python3.4 get-pip.py
  - python3.4 -m pip install -r pipeline/requirements.txt --user
  - python3.4 -m pip install nose irc --user
  - sudo cp test/example_rsyncd.conf /etc/rsyncd.conf
  - python3.4 -m pip install git+https://github.com/chfoo/huhhttp#egg=huhhttp --user

before_script:
  - curl -X PUT http://localhost:5984/archivebot

  # If ircd-hybrid is running (which currently happens with Ubuntu packages),
  # this will restart it.
  # If ircd-hybrid is not running (could happen in future), this will start it.
  - sudo /etc/init.d/ircd-hybrid restart
  - sudo /etc/init.d/rsync restart

services:
  - redis-server
  - couchdb

script:
  - bundle exec rake
  - python3.4 -m nose pipeline/
  - python3.4 test/integration_runner.py
